/**
 * Reusable fixture data for mobile item entry scenarios
 */

// Long list of grocery items for testing mobile focus behavior
export const LONG_GROCERY_LIST = [
  "Milk",
  "Eggs",
  "Bread",
  "Butter",
  "Cheese",
  "Apples",
  "Bananas",
  "Oranges",
  "Chicken breast",
  "Ground beef",
  "Pasta",
  "Rice",
  "Tomatoes",
  "Lettuce",
  "Carrots",
  "Onions",
  "Potatoes",
  "Yogurt",
  "Cereal",
  "Coffee",
  "Tea",
  "Juice",
  "Water",
  "Soda",
  "Chips",
  "Cookies",
  "Ice cream",
  "Frozen vegetables",
  "Frozen pizza",
  "Laundry detergent",
  "Dish soap",
  "Shampoo",
  "Toothpaste",
  "Paper towels",
  "Trash bags",
  "Aluminum foil",
  "Plastic wrap",
  "Ziploc bags",
  "Batteries",
  "Light bulbs",
];

// Long list of household chores for testing mobile focus behavior
export const LONG_CHORE_LIST = [
  "Vacuum living room",
  "Mop kitchen floor",
  "Clean bathroom sink",
  "Scrub toilet",
  "Wipe down counters",
  "Take out trash",
  "Do laundry",
  "Change bed sheets",
  "Dust furniture",
  "Water plants",
  "Mow lawn",
  "Weed garden",
  "Clean windows",
  "Organize closet",
  "Wash car",
  "Clean garage",
  "Fix leaky faucet",
  "Replace air filter",
  "Check smoke detectors",
  "Organize pantry",
  "Clean refrigerator",
  "Sweep porch",
  "Clean gutters",
  "Trim hedges",
  "Rake leaves",
  "Shovel driveway",
  "Wash windows",
  "Clean mirrors",
  "Dust light fixtures",
  "Vacuum stairs",
  "Mop bathroom floor",
  "Clean shower",
  "Wash dishes",
  "Clean microwave",
  "Organize fridge",
  "Take out recycling",
  "Clean oven",
  "Dust baseboards",
  "Clean door handles",
  "Wipe down appliances",
];
